import { ProjectTemplate } from '../types'

export const webPlatformTemplate: ProjectTemplate = {
  id: 'web-platform',
  name: '웹 플랫폼',
  icon: '🖥️',
  description: 'SaaS, 대시보드, 풀스택 플랫폼',
  category: 'platform',
  data: {
    ko: {
      project: {
        name: '',
        subtitle: '웹 플랫폼 개발 제안서',
        description: '고급 기능을 갖춘 풀스택 웹 플랫폼',
        date: '',
        client: '',
      },
      scope: {
        includes: [
          { id: '1', value: '사용자 인증 및 권한 관리' },
          { id: '2', value: '분석 기능이 포함된 대시보드' },
          { id: '3', value: '실시간 데이터 업데이트' },
          { id: '4', value: 'API 연동' },
          { id: '5', value: '관리자 관리 패널' },
          { id: '6', value: '이메일 알림 시스템' },
          { id: '7', value: '데이터 내보내기 (CSV, PDF)' },
        ],
        excludes: [
          { id: '1', value: '클라우드 인프라 비용' },
          { id: '2', value: '서드파티 API 비용' },
          { id: '3', value: '지속적인 유지보수' },
        ],
      },
      techStack: [
        { id: '1', category: '프론트엔드', name: 'Next.js + TypeScript' },
        { id: '2', category: '백엔드', name: 'Node.js + NestJS' },
        { id: '3', category: '데이터베이스', name: 'PostgreSQL + Redis' },
        { id: '4', category: '실시간', name: 'Socket.io' },
        { id: '5', category: '클라우드', name: 'AWS / GCP' },
        { id: '6', category: 'CI/CD', name: 'GitHub Actions' },
      ],
      phases: [
        {
          id: '1',
          name: '1단계: 아키텍처 및 디자인',
          description: '시스템 설계 및 프로토타이핑',
          amount: 500,
          items: [
            { id: '1', name: '시스템 아키텍처', detail: '기술 설계 문서', status: 'docs' },
            { id: '2', name: '데이터베이스 모델링', detail: 'ERD, API 명세', status: 'docs' },
            { id: '3', name: 'UI/UX 디자인', detail: '디자인 시스템', status: 'visual' },
          ],
        },
        {
          id: '2',
          name: '2단계: 핵심 백엔드',
          description: 'API 및 인프라',
          amount: 800,
          items: [
            { id: '1', name: '인증 시스템', detail: 'RBAC, OAuth', status: 'working' },
            { id: '2', name: '핵심 API', detail: '비즈니스 로직', status: 'working' },
            { id: '3', name: '데이터베이스 설정', detail: '마이그레이션, 시드', status: 'infra' },
            { id: '4', name: '실시간 엔진', detail: 'WebSocket', status: 'working' },
          ],
        },
        {
          id: '3',
          name: '3단계: 프론트엔드 플랫폼',
          description: '사용자 인터페이스 개발',
          amount: 700,
          items: [
            { id: '1', name: '대시보드', detail: '차트, 분석', status: 'visual' },
            { id: '2', name: '데이터 관리', detail: 'CRUD 인터페이스', status: 'working' },
            { id: '3', name: '실시간 업데이트', detail: '라이브 데이터 동기화', status: 'working' },
          ],
        },
        {
          id: '4',
          name: '4단계: 관리자 및 연동',
          description: '관리자 패널 및 외부 연동',
          amount: 500,
          items: [
            { id: '1', name: '관리자 대시보드', detail: '사용자/데이터 관리', status: 'working' },
            { id: '2', name: '외부 API', detail: '서드파티 연동', status: 'working' },
            { id: '3', name: '이메일 시스템', detail: '트랜잭션 이메일', status: 'working' },
          ],
        },
        {
          id: '5',
          name: '5단계: DevOps 및 런칭',
          description: '인프라 및 배포',
          amount: 500,
          items: [
            { id: '1', name: 'CI/CD 파이프라인', detail: '자동화 배포', status: 'infra' },
            { id: '2', name: '모니터링', detail: '로그, 알림', status: 'infra' },
            { id: '3', name: '보안 감사', detail: '침투 테스트', status: 'stabilization' },
            { id: '4', name: '문서화', detail: 'API 문서, 가이드', status: 'docs' },
          ],
        },
      ],
      paymentTerms: [
        { id: '1', phase: '계약금', condition: '계약 체결 시', amount: 900 },
        { id: '2', phase: '2단계', condition: '백엔드 완료 시', amount: 700 },
        { id: '3', phase: '4단계', condition: '기능 완료 시', amount: 700 },
        { id: '4', phase: '잔금', condition: '프로덕션 런칭 시', amount: 700 },
      ],
      schedule: [
        { id: '1', phase: '1단계', duration: '2주', deliverable: '아키텍처, 디자인' },
        { id: '2', phase: '2단계', duration: '5주', deliverable: 'API 서버' },
        { id: '3', phase: '3단계', duration: '4주', deliverable: '프론트엔드' },
        { id: '4', phase: '4단계', duration: '3주', deliverable: '관리자, 연동' },
        { id: '5', phase: '5단계', duration: '2주', deliverable: '프로덕션 준비' },
      ],
      terms: [
        { id: '1', label: '하자보수', value: '런칭 후 6개월' },
        { id: '2', label: '소스코드', value: '전체 소유권 이전' },
        { id: '3', label: '문서화', value: '기술 및 사용자 문서 포함' },
        { id: '4', label: '교육', value: '4시간 포함' },
      ],
      expansions: [
        { id: '1', feature: '모바일 앱', description: 'React Native 동반 앱', amount: 1500 },
        { id: '2', feature: 'AI 기능', description: 'ML 기반 분석', amount: 800 },
        { id: '3', feature: '화이트라벨', description: '멀티테넌트 지원', amount: 600 },
      ],
    },
    en: {
      project: {
        name: '',
        subtitle: 'Web Platform Development Proposal',
        description: 'Full-stack web platform with advanced features',
        date: '',
        client: '',
      },
      scope: {
        includes: [
          { id: '1', value: 'User authentication & authorization' },
          { id: '2', value: 'Dashboard with analytics' },
          { id: '3', value: 'Real-time data updates' },
          { id: '4', value: 'API integrations' },
          { id: '5', value: 'Admin management panel' },
          { id: '6', value: 'Email notification system' },
          { id: '7', value: 'Data export (CSV, PDF)' },
        ],
        excludes: [
          { id: '1', value: 'Cloud infrastructure costs' },
          { id: '2', value: 'Third-party API fees' },
          { id: '3', value: 'Ongoing maintenance' },
        ],
      },
      techStack: [
        { id: '1', category: 'Frontend', name: 'Next.js + TypeScript' },
        { id: '2', category: 'Backend', name: 'Node.js + NestJS' },
        { id: '3', category: 'Database', name: 'PostgreSQL + Redis' },
        { id: '4', category: 'Real-time', name: 'Socket.io' },
        { id: '5', category: 'Cloud', name: 'AWS / GCP' },
        { id: '6', category: 'CI/CD', name: 'GitHub Actions' },
      ],
      phases: [
        {
          id: '1',
          name: 'Phase 1: Architecture & Design',
          description: 'System design and prototyping',
          amount: 500,
          items: [
            { id: '1', name: 'System architecture', detail: 'Technical design doc', status: 'docs' },
            { id: '2', name: 'Database modeling', detail: 'ERD, API specs', status: 'docs' },
            { id: '3', name: 'UI/UX design', detail: 'Design system', status: 'visual' },
          ],
        },
        {
          id: '2',
          name: 'Phase 2: Core Backend',
          description: 'API and infrastructure',
          amount: 800,
          items: [
            { id: '1', name: 'Auth system', detail: 'RBAC, OAuth', status: 'working' },
            { id: '2', name: 'Core APIs', detail: 'Business logic', status: 'working' },
            { id: '3', name: 'Database setup', detail: 'Migrations, seeds', status: 'infra' },
            { id: '4', name: 'Real-time engine', detail: 'WebSocket', status: 'working' },
          ],
        },
        {
          id: '3',
          name: 'Phase 3: Frontend Platform',
          description: 'User interface development',
          amount: 700,
          items: [
            { id: '1', name: 'Dashboard', detail: 'Charts, analytics', status: 'visual' },
            { id: '2', name: 'Data management', detail: 'CRUD interfaces', status: 'working' },
            { id: '3', name: 'Real-time updates', detail: 'Live data sync', status: 'working' },
          ],
        },
        {
          id: '4',
          name: 'Phase 4: Admin & Integration',
          description: 'Admin panel and external integrations',
          amount: 500,
          items: [
            { id: '1', name: 'Admin dashboard', detail: 'User/data management', status: 'working' },
            { id: '2', name: 'External APIs', detail: 'Third-party integrations', status: 'working' },
            { id: '3', name: 'Email system', detail: 'Transactional emails', status: 'working' },
          ],
        },
        {
          id: '5',
          name: 'Phase 5: DevOps & Launch',
          description: 'Infrastructure and deployment',
          amount: 500,
          items: [
            { id: '1', name: 'CI/CD pipeline', detail: 'Automated deployment', status: 'infra' },
            { id: '2', name: 'Monitoring', detail: 'Logs, alerts', status: 'infra' },
            { id: '3', name: 'Security audit', detail: 'Penetration testing', status: 'stabilization' },
            { id: '4', name: 'Documentation', detail: 'API docs, guides', status: 'docs' },
          ],
        },
      ],
      paymentTerms: [
        { id: '1', phase: 'Contract', condition: 'Upon signing', amount: 900 },
        { id: '2', phase: 'Phase 2', condition: 'Backend completion', amount: 700 },
        { id: '3', phase: 'Phase 4', condition: 'Feature complete', amount: 700 },
        { id: '4', phase: 'Final', condition: 'Production launch', amount: 700 },
      ],
      schedule: [
        { id: '1', phase: 'Phase 1', duration: '2 weeks', deliverable: 'Architecture, design' },
        { id: '2', phase: 'Phase 2', duration: '5 weeks', deliverable: 'API server' },
        { id: '3', phase: 'Phase 3', duration: '4 weeks', deliverable: 'Frontend' },
        { id: '4', phase: 'Phase 4', duration: '3 weeks', deliverable: 'Admin, integrations' },
        { id: '5', phase: 'Phase 5', duration: '2 weeks', deliverable: 'Production ready' },
      ],
      terms: [
        { id: '1', label: 'Warranty', value: '6 months after launch' },
        { id: '2', label: 'Source code', value: 'Full ownership transfer' },
        { id: '3', label: 'Documentation', value: 'Technical & user docs included' },
        { id: '4', label: 'Training', value: '4 hours included' },
      ],
      expansions: [
        { id: '1', feature: 'Mobile app', description: 'React Native companion app', amount: 1500 },
        { id: '2', feature: 'AI features', description: 'ML-powered analytics', amount: 800 },
        { id: '3', feature: 'White-label', description: 'Multi-tenant support', amount: 600 },
      ],
    },
  },
}
